# Generated by Django 5.2.12 on 2026-03-18 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoryOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("child_name", models.CharField(max_length=100)),
                ("child_age", models.IntegerField()),
                (
                    "child_gender",
                    models.CharField(
                        choices=[("boy", "ولد"), ("girl", "بنت")], max_length=10
                    ),
                ),
                ("favorite_animal", models.CharField(max_length=100)),
                (
                    "wish",
                    models.CharField(
                        choices=[
                            ("brave", "شجاع"),
                            ("kind", "طيب القلب"),
                            ("smart", "ذكي"),
                            ("curious", "فضولي ومحب للاكتشاف"),
                            ("strong", "قوي"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("adventure", "مغامرة في الغابة"),
                            ("magic", "عالم سحري"),
                            ("animals", "مملكة الحيوانات"),
                            ("space", "رحلة إلى الفضاء"),
                            ("ocean", "أعماق البحر"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("story_text", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("paid", "Paid"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
