# Generated by Django 5.2.12 on 2026-03-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyorder",
            name="audio_file",
            field=models.FileField(blank=True, upload_to="story_audio/"),
        ),
        migrations.AddField(
            model_name="storyorder",
            name="audio_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
