# Generated by Django 5.2.12 on 2026-03-19 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0002_storyorder_audio_file_storyorder_audio_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyorder",
            name="illustrations_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StoryIllustration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scene_index", models.IntegerField()),
                ("scene_description", models.TextField()),
                ("image", models.ImageField(upload_to="story_illustrations/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="illustrations",
                        to="stories.storyorder",
                    ),
                ),
            ],
            options={
                "ordering": ["scene_index"],
            },
        ),
    ]
