# Generated by Django 5.2.12 on 2026-03-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0003_storyorder_illustrations_status_storyillustration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storyillustration",
            options={"ordering": ["paragraph_index", "scene_index"]},
        ),
        migrations.AddField(
            model_name="storyillustration",
            name="paragraph_index",
            field=models.IntegerField(default=0),
        ),
    ]
