# Generated by Django 5.2.12 on 2026-03-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0004_alter_storyillustration_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyorder",
            name="story_moral",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="storyorder",
            name="story_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
