# Generated by Django 5.2.12 on 2026-03-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0006_storyorder_video_status_storyvideoclip"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyorder",
            name="child_photo",
            field=models.ImageField(blank=True, upload_to="child_photos/"),
        ),
    ]
