# Generated by Django 5.2.12 on 2026-03-19 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0007_storyorder_child_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyorder",
            name="cover_illustration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="stories.storyillustration",
            ),
        ),
    ]
